LEGINabroad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.sitemaps.views import sitemap
from legin_abroad.sitemaps import ArticleSitemap, StaticViewSitemap, SectionSitemap #, TagSitemap
from legin_abroad import views as la_views
from django.views.static import serve


#from . import views

sitemaps = {
	'static': StaticViewSitemap,
	'article': ArticleSitemap,
	'section': SectionSitemap,
}

urlpatterns = [
    path('admin_LA/', admin.site.urls),
    path('en/', include('en_legin_abroad.urls')),
    path('', include('legin_abroad.urls')),
    
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

en_legin_abroad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "en_legin_abroad"

urlpatterns = [
    path("", views.index, name="en_index"),
    path("search", views.SearchView.as_view(), name="en_search"),
    path("sections/search", views.SearchView.as_view(), name="en_search"),
    path("<slug:sslug>/search", views.SearchView.as_view(), name="en_search"),
    path("tag/<slug:tag_slug>/search", views.tag_search, name="en_search"),
    path("sections/<slug:sslug>", views.section, name="en_section"),  # Sections url
    path("sections", views.SectionsListView.as_view(), name="en_sections"),
    path("tag/<slug:tag_slug>/", views.index, name="en_article_by_tag"),
    path("about", views.about, name="en_about"),
    path("<slug:sslug>/<slug:slug>", views.ArticleDetailView.as_view(), name="en_article"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legin_abroad_base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# from django.contrib.sitemaps.views import sitemap
# from legin_abroad.sitemaps import ArticleSitemap, StaticViewSitemap, SectionSitemap  #, TagSitemap

# sitemaps = {
#     'static': StaticViewSitemap,
#     'article': ArticleSitemap,
#     'section': SectionSitemap,
# }
urlpatterns = [
    path("admin_LA/", admin.site.urls),
    path("", include("en_legin_abroad.urls")),
    # path('', include('legin_abroad.urls')),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

en_legin_abroad/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from taggit.managers import TaggableManager


class EnSection(models.Model):
    """Section of the blog"""

    name = models.CharField(max_length=70)
    sslug = models.SlugField(unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    thumb = ProcessedImageField(
        upload_to="thumbs_/%Y/%m/",
        processors=[Thumbnail(800, 458)],
        blank=True,
        null=True,
        format="PNG",
        options={"quality": 90},
    )
    description = RichTextUploadingField(
        blank=True,
        null=True,
        config_name="default",
        external_plugin_resources=[
            (
                "youtube",
                "/static/youtube/youtube/",
                "plugin.js",
            ),
        ],
    )

    def __str__(self):
        """returns string rev. of the model"""
        return self.name

    def get_absolute_url(self):
        return reverse("en_legin_abroad:en_section", kwargs={"sslug": self.sslug})


class EnPublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


class EnArticle(models.Model):
    """Articles  under section"""

    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    section = models.ForeignKey(EnSection, on_delete=models.CASCADE, null=False, blank=False)
    topic = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=False)
    body = RichTextUploadingField(
        blank=True,
        null=True,
        config_name="default",
        external_plugin_resources=[
            (
                "youtube",
                "/static/youtube/youtube/",
                "plugin.js",
            ),
        ],
    )
    date_added = models.DateTimeField()

    thumb = ProcessedImageField(
        upload_to="thumbs_/%Y/%m/",
        processors=[Thumbnail(800, 458)],
        blank=True,
        null=True,
        format="PNG",
        options={"quality": 90},
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    objects = models.Manager()  # The default manager.
    published = EnPublishedManager()  # custom manager.
    tags = TaggableManager()

    class Meta:
        verbose_name_plural = "en_articles"

    def __str__(self):
        """returns string rev. of the model"""
        return self.body[:200] + "..."

    def get_absolute_url(self):
        return reverse("en_legin_abroad:en_article", kwargs={"sslug": self.section.sslug, "slug": self.slug})

en_legin_abroad/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

en_legin_abroad/views.py
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, ListView, View
from taggit.models import Tag

from .forms import SearchForm
from .models import EnArticle, EnSection


def index(request, tag_slug=None):
    """Home page"""
    sections = EnSection.objects.all().order_by("date_added")
    section = EnSection.objects.all()
    articles = EnArticle.objects.all().order_by("-date_added").filter(status="published")
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        articles = articles.filter(tags__in=[tag])

    paginator = Paginator(articles, 10)  # 10 posts on each page
    page = request.GET.get("page")

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If a page is not an integer, deliver the first page
        articles = paginator.page(1)
    except EmptyPage:
        # If the page is out of range deliver last page of results
        articles = paginator.page(paginator.num_pages)
    context = {"sections": sections, "section": section, "articles": articles, "tag": tag}
    return render(request, "en_legin_abroad/en_index.html", context)


class SectionsListView(ListView):
    model = EnSection
    template_name = "en_legin_abroad/en_sections.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all sections
        context["sections"] = EnSection.objects.all()

        return context


def section(request, sslug):
    sections = EnSection.objects.all()
    section = get_object_or_404(EnSection, sslug=sslug)
    articles = section.enarticle_set.order_by("-date_added").filter(status="published")
    paginator = Paginator(articles, 5)
    page = request.GET.get("page")
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        articles = paginator.page(paginator.num_pages)

    context = {"sections": sections, "section": section, "articles": articles}

    return render(request, "en_legin_abroad/en_section.html", context)


class ArticleDetailView(DetailView):
    """
    View for displaying detailed information about a single article.
    Handles article display with related tags and similar articles suggestions.
    """

    model = EnArticle

    def get(self, request, slug, tag_slug=None, *args, **kwargs):
        """
        Handles GET requests for article detail view.

        Args:
            request: The HTTP request
            slug: The article's slug identifier
            tag_slug: Optional tag slug for filtering
            *args: Variable length argument list
            **kwargs: Arbitrary keyword arguments

        Returns:
            Rendered article detail template with article and related content
        """
        context = {}
        article = get_object_or_404(EnArticle, slug=slug, status="published")
        tag = article.tags.all()
        article_tags_ids = article.tags.values_list("id", flat=True)
        similar_articles = (
            EnArticle.objects.all().filter(status="published", tags__in=article_tags_ids).exclude(id=article.id)
        )
        similar_articles = similar_articles.annotate(same_tags=Count("tags")).order_by("-same_tags")[:3]

        context["article"] = article
        context["tag"] = tag
        context["similar_articles"] = similar_articles
        context["sections"] = EnSection.objects.all()

        return render(request, self.template_name, context)

    template_name = "en_legin_abroad/en_article.html"


class SearchView(View):
    template_name = "en_legin_abroad/en_search.html"

    def get(self, request, *args, **kwargs):
        context = {}
        form = SearchForm()
        query = None
        results = []
        articles = EnArticle.objects.all().order_by("-date_added").filter(status="published")

        if "query" in request.GET:
            form = SearchForm(request.GET)

            if form.is_valid():
                query = form.cleaned_data["query"]
                search_vector = SearchVector("topic", "body", "section")
                search_query = SearchQuery(query)
                results = (
                    EnArticle.objects.annotate(
                        search=search_vector,
                        rank=SearchRank(search_vector, search_query),
                    )
                    .filter(search=search_query, status="published")
                    .order_by("-rank")
                )
        resultss = results
        resultss = list(dict.fromkeys(resultss))

        context["article"] = EnArticle.objects.all().order_by("-date_added").filter(status="published")
        context["articles"] = articles
        context["sections"] = EnSection.objects.all()
        context["resultss"] = resultss
        context["results"] = results
        context["form"] = form
        context["query"] = query

        return render(request, self.template_name, context)


def tag_search(request, tag_slug=None):
    form = SearchForm()
    query = None
    results = []
    sections = EnSection.objects.all()
    tag = get_object_or_404(Tag, slug=tag_slug)

    if "query" in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data["query"]
            search_vector = (
                SearchVector("topic", weight="A")
                + SearchVector("body", weight="B")
                + SearchVector("tags", weight="C")
                + SearchVector("section", weight="A")
            )
            search_query = SearchQuery(query)
            results = (
                EnArticle.objects.annotate(
                    search=search_vector,
                    rank=SearchRank(search_vector, search_query),
                )
                .filter(search=search_query, status="published")
                .order_by("-rank")
            )

    context = {
        "form": form,
        "query": query,
        "results": results,
        "sections": sections,
        "section": section,
        "tag": tag,
    }

    return render(request, "en_legin_abroad/en_search.html", context)


def about(request):
    sections = EnSection.objects.all()
    articles = EnArticle.objects.all().order_by("-date_added").filter(status="published")
    context = {"sections": sections, "section": section, "articles": articles}

    return render(request, "en_legin_abroad/en_about.html", context)

en_legin_abroad/templates/en_legin_abroad/en_article.html
{% extends "en_legin_abroad/en_base.html" %}
{% load static %}

<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<head>
  <title>{{ article.topic }}</title>
</head>>
{% block body_class %}article-detail-page{% endblock %}
{% block content %}
  <nav aria-label="breadcrumb" id="breadcrumb">
    <ol class="breadcrumb bg-white ml">
      <li class="breadcrumb-item"><a class="navbar-brand mr-auto" style='color: #6A9C20;' href="{% url 'en_legin_abroad:en_index' %}">Home</a></li>
      <li class="breadcrumb-item"><a class="navbar-brand mr-auto" style='color: #6A9C20;' href="{% url 'en_legin_abroad:en_sections' %}">Topics</a></li>
      <li class="breadcrumb-item"><a class="navbar-brand mr-auto" style='color: #6A9C20;' href="{{article.section.get_absolute_url}}">{{ article.section.name }}</a></li>
    </ol>
  </nav>
  <div id="article">
    <div class="part">
    {% if article.thumb %}
      <a href="{{article.get_absolute_url}}"><img class='m-auto' style="position: center" src="{{ article.thumb.url }}"></a>
    {% endif %}
    <h1>{{ article.topic }}</h1>

        <strong>{{ article.date_added|date:'F, d, Y' }}</strong>

      <p class="article">{{ article.body|safe }}</p><br>
      </div>
      <div class="foot">
        {% if article.tags %}
          {% for tag in article.tags.all %}
            <a class="tag d-inline-flex p-2" href="{% url "en_legin_abroad:en_article_by_tag" tag.slug %}">#{{ tag.name }}</a>
          {% endfor %}
        {% endif %}
      </div>

      <h3>Similar articles:</h3>
      {% for article in similar_articles %}
        <p>
          <a class="artic"  id="artic" href="{{ article.get_absolute_url }}">{{ article.topic|truncatewords:7 }}</a>
        </p>
      {% empty %}
        None...
      {% endfor %}
    </div>


  <p>
    <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    <a href="http://www.reddit.com/submit?url=http://{{ request.build_absolute_uri }}/">  Reddit</a>
    <!--<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}/">Facebook</a> -->
  </p>
  <hr/>
  <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
  </div>
{% endblock content %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

en_legin_abroad/templates/en_legin_abroad/en_form.html
{% extends 'en_legin_abroad/en_base.html' %}
{% block content %}

  {% if title %}
    <h1>{{ title }}</h1>
  {% endif %}
  <form method='POST' action='.'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Send</button>
  </form>

{% endblock %}

en_legin_abroad/templates/en_legin_abroad/en_index.html
{% extends "en_legin_abroad/en_base.html" %}
{% load static %}

<body>
  {% block content %}
      <div class="article_list">
        {% if tag %}
          <h2>Articles with tag: "{{ tag.name }}":</h2>
        {% endif %}
        {% for article in articles %}
          <div class="shared-container article-container" id="article-card">
            <h1><a class='artic' href="{{ article.get_absolute_url }}">{{ article.topic }}</a></h1>
            <a class="sect" href="{{ article.section.get_absolute_url }}">{{ article.section }}</a></br>
            {% if article.thumb %}
              <a href="{{ article.get_absolute_url }}"><img class='thumb' src="{{ article.thumb.url }}"></a></br>
            {% endif %}
            <p><a class="artic" href="{{ article.get_absolute_url }}">{{ article|safe }}</a></p>
            {% load i18n %}
            <br><strong>{{ article.date_added|date:'F, d, Y' }}</strong>
             <br>  <p class="tags">
              {% for tag in article.tags.all %}
                <a class="tag d-inline-flex p-2" href="{% url "en_legin_abroad:en_article_by_tag" tag.slug %}">#{{ tag.name }}</a>
              {% endfor %}
            </p>
          </div>
        {% empty %}
          <li>
            There is no entries for the current topic.
          </li>
        {% endfor %}
      </div>

    <div class="paginator">
      {% include "en_legin_abroad/en_pagination.html" with page=articles %}
    </div>
  {% endblock content %}
</body>

en_legin_abroad/templates/en_legin_abroad/en_navbar.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}


<head>
    <!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'nav.css' %}" />
    <link rel="stylesheet" href="{% static 'media.css' %}" />
</head>

<nav class="navbar navbar-expand-md fixed-top" id="navbar" >
<div class="container-fluid">
    <div class="pos-f-t">
      <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
          <ul class="nav-item">
            {% for section in sections %}
              <a href="{{section.get_absolute_url}}"> {{section }} </a>
            {% empty %}
              <li>
                There is no entries for the current topic.
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>

    </div>
    <!--<a class="nav-button nav-sidepanel-button show-menu" href="#sidepanel" title="Navigation">
				<span class="icon icon-menu"></span>
			</a>-->

    <ul class='nav navbar-nav'>
      <ul class='navbar-brand'>
        <div class='row ml'>
          <a class="navbar-brand" id="banner" href="{% url 'en_legin_abroad:en_index' %}">leginabroad.com</a>
          <button class="navbar-toggler  mr-auto" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggler navigation">
              <div class="container" onclick="myFunction(this)">
              <div class="bar1"></div>
              <div class="bar2"></div>
              <div class="bar3"></div>
          </div>          <script> function myFunction(x) {
            x.classList.toggle("change");
        }</script>
          </button>
          <div class='collapse navbar-collapse' id='navbarMenu'>
            <ul class="nav-item">
              <a class='nav-link-offset-5 mr-5' href="{% url 'en_legin_abroad:en_about' %}">ABOUT</a>
              {% for section in sections %}
                <a href="{{section.get_absolute_url}}" class='nav-link-offset-5 mr-5'> {{section}} </a>
              {% empty %}
              </ul>
              <li>
                There is no entries for the current topic.
              </li>
            {% endfor %}
          </div>
        </div>
      </ul>
    </ul>
    
    <form class='form-inline ml-auto' method="GET" action="search" style="padding: 2px 4px">
        <input class='form-control mr-2 col-sm-4 col-md-4 col-lg-8 ' id="searchInput" name="query" value="{{request.GET.query}}" placeholder="search" aria-label="Search">
        <button class="btn success" id="submitButton" type="submit">
          Search
        </button>
    </form>

    <!-- Show Search Button -->
     <button type="button" id="toggleButton" class="btn btn-secondary">
        Search
     </button>
  </div>
</div>
</nav>

<script>
  window.onscroll = function() {myFunction()};
  
  function myFunction() {
    var winScroll = document.body.scrollTop || document.documentElement.scrollTop;
    var height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
    var scrolled = (winScroll / height) * 100;
    document.getElementById("myBar").style.width = scrolled + "%";
  }

  const form = document.querySelector('form');
  const toggleButton = document.getElementById('toggleButton');

  toggleButton.addEventListener('click', function () {
    form.classList.toggle('show-search');
  });

</script> 

en_legin_abroad/templates/en_legin_abroad/en_search.html
{% extends "en_legin_abroad/en_base.html" %}
{% load static %}

<head>
  
</head>

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Articles with "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        {% if total_results == 1 %}
          Found {{ total_results }} match
        {% else %}
          
          Found {{ total_results }} matches
        {% endif %}
      {% endwith %}
    </h3>
    {% for article in resultss %}
      <div class="results">
        <h4><a class="res" href="{{ article.get_absolute_url }}">{{ article.topic }}</a></h4>

          {{ article.results.count }}

        {{ article.body|safe|truncatewords:5 }}
      </div>
      {% empty %}
        <p id="search_text">Sorry, no results has been found...</p>
      {% endfor %}
      <p><a id="search_text_link" href="{% url "en_legin_abroad:en_search" %}">Search more</a></p>
    {% else %}
    <h1>Articles search</h1>

    <form class='form-inline ml-auto' method="GET" action="search">
        <input class='form-control mr-2 col-sm-4 col-md-4 col-lg-8' name="query" value="{{request.GET.query}}" placeholder="search" aria-label="Search">
        <!--<input class='form-control mr-2 col-sm-4 col-md-4 col-lg-8' name="q" value="{{request.GET.q}}" placeholder="пошук" aria-label="Пошук">-->
        <button class="btn btn-success" type="submit">
          Search
        </button>
    </form>
  {% endif %}
{% endblock %}

en_legin_abroad/templates/en_legin_abroad/en_section.html
{% extends "en_legin_abroad/en_base.html" %}
{% load static %}
<head >
    <link rel="stylesheet" href="{% static 'style.css' %}" />

</head>
<body>
  {% block content %}

      <nav>
        <ol class="breadcrumb bg-white">
          <li class="breadcrumb-item"><a class="navbar-brand mr-auto" href="{% url 'en_legin_abroad:en_index' %}">Home</a></li>
          <li class="breadcrumb-item"><a class="navbar-brand mr-auto" href="{% url 'en_legin_abroad:en_sections' %}">Topics</a></li>
          <li class="breadcrumb-item "><a class="navbar-brand mr-auto" href="{{section.get_absolute_url}}">{{section}}</a></li>
        </ol>
      </nav>
      <div class="article_list">
        {% for article in articles %}
          <div class="shared-container article-container">
            <h1><a class='artic' href="{{ article.get_absolute_url }}">{{ article.topic }}</a></h1>
            <a class="sect" href="{{ article.section.get_absolute_url }}">{{ article.section }}</a></br>
            {% if article.thumb %}
              <a href="{{ article.get_absolute_url }}"><img class='thumb' src="{{ article.thumb.url }}"></a></br>
            {% endif %}
            <p><a class="artic" href="{{ article.get_absolute_url }}">{{ article|safe }}</a></p>
            {% load i18n %}
            <strong>{{ article.date_added|date:'F, d, Y' }}</strong><br>
            <p class="tags">
              {% for tag in article.tags.all %}
                <a class="tag d-inline-flex p-2" href="{% url "en_legin_abroad:en_article_by_tag" tag.slug %}">#{{ tag.name }}</a>
              {% endfor %}
            </p>
          </div>
        {% empty %}
          <li>
            There is no entries for the current topic.
          </li>

        {% endfor %}
      </div>
    <div class="paginator">
      {% include "en_legin_abroad/en_pagination.html" with page=articles %}
    </div>
  {% endblock content %}
</body>

en_legin_abroad/templates/en_legin_abroad/en_sections.html
{% extends "en_legin_abroad/en_base.html" %}
{% load static %}

<head>
<!--  <link rel="stylesheet" href="{% static 'css/sections.css' %}" />-->
</head>
<body>
  {% block content %}
    <nav>
        <ol class="breadcrumb bg-white">
          <li class="breadcrumb-item"><a class="navbar-brand mr-auto" href="{% url 'en_legin_abroad:en_index' %}">Home</a></li>
        </ol>
      </nav>
    <div class="section-grid-container">
  
        {% for section in sections %}
          <div class='shared-container section-container'>
            <h2><a id='sections' href="{{section.get_absolute_url}}">{{ section.name }}</a></h2>
            {% if section.thumb %}
              <a href="{{section.get_absolute_url}}"><img class='m-auto ses' style="position: center" src="{{ section.thumb.url }}"></a>
            {% endif %}
            {% if section.description %}
              <p><a class="sections" href="{{ section.get_absolute_url }}">{{ section.description|safe|truncatewords:150 }}</a></p>
            {% endif %}
          </div>
        {% endfor %}
    </div>
  {% endblock content %}
</body>

en_legin_abroad/templates/en_legin_abroad/en_side_bar.html
<!DOCTYPE html>
{% load static %}
<head>
<!--    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/side_bar_style.css' %}">


</head>
<body>


<a class="btn btn sects" href="{% url 'en_legin_abroad:en_sections' %}" role="button">TOPICS</a>
  <!--<iframe width="500" height="450" src="https://embed.windy.com/embed2.html?lat=35.599&lon=140.081&zoom=8&level=surface&overlay=rain&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=35.599&detailLon=140.081&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1" frameborder="1"></iframe>-->
  
</body>